{{- if .Values.jboss.service }}
{{- with .Values.jboss.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jboss.fullname" $ }}
  labels:
    {{- include "jboss.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "jboss.selectorLabels" $ | nindent 4 }}
  type: {{ .type }}
  {{- if .ports }}
  ports:
    {{- toYaml .ports | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
