apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jboss.fullname" $ }}
  labels:
    {{- include "jboss.labels" $ | nindent 4 }}
spec:
  {{- with .Values.jboss }}
  {{- $jboss := . }}
  replicas: {{ .replicaCount | default 1 }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "jboss.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jboss.selectorLabels" $ | nindent 8 }}
    spec:
      containers:
        {{- with .containers.jboss }}
        - name: {{ $.Chart.Name }}
          {{- with .image }}
          image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
          {{- end }}
          {{- if $jboss.service }}
          ports:
            {{- range $jboss.service.ports }}
            - containerPort: {{ .targetPort }}
              name: {{ .name }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- end }}
          {{- if .livenessProbe }}
          livenessProbe:
          {{- toYaml .livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .readinessProbe }}
          readinessProbe:
          {{- toYaml .readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .resources }}
          resources:
          {{- toYaml .resources | nindent 12 }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
          {{- toYaml .volumeMounts | nindent 12 }}
          {{- end }}
        {{- end }}
      hostname: {{ .hostname | default "jboss" }}
      restartPolicy: Always
      {{- if .volumes }}
      volumes:
      {{- toYaml .volumes | nindent 8 }}
      {{- end }}
  {{- end }}
